# (Infinitiv, Präteritum, Partizip II)
# Source: https://www.verbformen.de/unregelmaessige-verben/
IRREGULAR_VERBS = [
    ('backen', 'buk', 'gebacken'), ('befehlen', 'befahl', 'befohlen'),
    ('beginnen', 'begann', 'begonnen'), ('beißen', 'biss', 'gebissen'),
    ('bergen', 'barg', 'geborgen'), ('bersten', 'barst', 'geborsten'),
    ('bewegen', 'bewog', 'bewogen'), ('biegen', 'bog', 'gebogen'),
    ('bieten', 'bot', 'geboten'), ('binden', 'band', 'gebunden'),
    ('bitten', 'bat', 'gebeten'), ('blasen', 'blies', 'geblasen'),
    ('bleiben', 'blieb', 'geblieben'), ('braten', 'briet', 'gebraten'),
    ('brechen', 'brach', 'gebrochen'), ('brennen', 'brannte', 'gebrannt'),
    ('bringen', 'brachte', 'gebracht'), ('denken', 'dachte', 'gedacht'),
    ('dreschen', 'drosch', 'gedroschen'), ('dringen', 'drang', 'gedrungen'),
    ('dürfen', 'durfte', 'gedurft'), ('empfangen', 'empfing', 'empfangen'),
    ('empfehlen', 'empfahl', 'empfohlen'), ('empfinden', 'empfand', 'empfunden'),
    ('erlöschen', 'erlosch', 'erloschen'), ('erschrecken', 'erschrak', 'erschrocken'),
    ('essen', 'aß', 'gegessen'), ('fahren', 'fuhr', 'gefahren'),
    ('fallen', 'fiel', 'gefallen'), ('fangen', 'fing', 'gefangen'),
    ('fechten', 'focht', 'gefochten'), ('finden', 'fand', 'gefunden'),
    ('fliegen', 'flog', 'geflogen'), ('fliehen', 'floh', 'geflohen'),
    ('fließen', 'floss', 'geflossen'), ('fressen', 'fraß', 'gefressen'),
    ('frieren', 'fror', 'gefroren'), ('gären', 'gor', 'gegoren'),
    ('gebären', 'gebar', 'geboren'), ('geben', 'gab', 'gegeben'),
    ('gedeihen', 'gedieh', 'gediehen'), ('gehen', 'ging', 'gegangen'),
    ('gelingen', 'gelang', 'gelungen'), ('gelten', 'galt', 'gegolten'),
    ('genesen', 'genas', 'genesen'), ('genießen', 'genoss', 'genossen'),
    ('geschehen', 'geschah', 'geschehen'), ('gewinnen', 'gewann', 'gewonnen'),
    ('gießen', 'goss', 'gegossen'), ('gleichen', 'glich', 'geglichen'),
    ('gleiten', 'glitt', 'geglitten'), ('graben', 'grub', 'gegraben'),
    ('greifen', 'griff', 'gegriffen'), ('haben', 'hatte', 'gehabt'),
    ('halten', 'hielt', 'gehalten'), ('hängen', 'hing', 'gehangen'),
    ('hauen', 'hieb', 'gehauen'), ('heben', 'hob', 'gehoben'),
    ('heißen', 'hieß', 'geheißen'), ('helfen', 'half', 'geholfen'),
    ('kennen', 'kannte', 'gekannt'), ('klingen', 'klang', 'geklungen'),
    ('kommen', 'kam', 'gekommen'), ('können', 'konnte', 'gekonnt'),
    ('kriechen', 'kroch', 'gekrochen'), ('laden', 'lud', 'geladen'),
    ('lassen', 'ließ', 'gelassen'), ('laufen', 'lief', 'gelaufen'),
    ('leiden', 'litt', 'gelitten'), ('leihen', 'lieh', 'geliehen'),
    ('lesen', 'las', 'gelesen'), ('liegen', 'lag', 'gelegen'),
    ('lügen', 'log', 'gelogen'), ('mahlen', 'mahlte', 'gemahlen'),
    ('meiden', 'mied', 'gemieden'), ('melken', 'molk', 'gemolken'),
    ('messen', 'maß', 'gemessen'), ('misslingen', 'misslang', 'misslungen'),
    ('mögen', 'mochte', 'gemocht'), ('müssen', 'musste', 'gemusst'),
    ('nehmen', 'nahm', 'genommen'), ('nennen', 'nannte', 'genannt'),
    ('pfeifen', 'pfiff', 'gepfiffen'), ('raten', 'riet', 'geraten'),
    ('reiben', 'rieb', 'gerieben'), ('reißen', 'riss', 'gerissen'),
    ('reiten', 'ritt', 'geritten'), ('rennen', 'rannte', 'gerannt'),
    ('riechen', 'roch', 'gerochen'), ('ringen', 'rang', 'gerungen'),
    ('rinnen', 'rann', 'geronnen'), ('rufen', 'rief', 'gerufen'),
    ('saufen', 'soff', 'gesoffen'), ('saugen', 'sog', 'gesogen'),
    ('schaffen', 'schuf', 'geschaffen'), ('scheiden', 'schied', 'geschieden'),
    ('scheinen', 'schien', 'geschienen'), ('schelten', 'schalt', 'gescholten'),
    ('scheren', 'schor', 'geschoren'), ('schieben', 'schob', 'geschoben'),
    ('schießen', 'schoss', 'geschossen'), ('schlafen', 'schlief', 'geschlafen'),
    ('schlagen', 'schlug', 'geschlagen'), ('schleichen', 'schlich', 'geschlichen'),
    ('schleifen', 'schliff', 'geschliffen'), ('schließen', 'schloss', 'geschlossen'),
    ('schlingen', 'schlang', 'geschlungen'), ('schmeißen', 'schmiss', 'geschmissen'),
    ('schmelzen', 'schmolz', 'geschmolzen'), ('schneiden', 'schnitt', 'geschnitten'),
    ('schreiben', 'schrieb', 'geschrieben'), ('schreien', 'schrie', 'geschrien'),
    ('schreiten', 'schritt', 'geschritten'), ('schweigen', 'schwieg', 'geschwiegen'),
    ('schwimmen', 'schwamm', 'geschwommen'), ('schwinden', 'schwand', 'geschwunden'),
    ('schwingen', 'schwang', 'geschwungen'), ('schwören', 'schwor', 'geschworen'),
    ('sehen', 'sah', 'gesehen'), ('sein', 'war', 'gewesen'),
    ('senden', 'sandte', 'gesandt'), ('singen', 'sang', 'gesungen'),
    ('sinken', 'sank', 'gesunken'), ('sinnen', 'sann', 'gesonnen'),
    ('sitzen', 'saß', 'gesessen'), ('sollen', 'sollte', 'gesollt'),
    ('spinnen', 'spann', 'gesponnen'), ('sprechen', 'sprach', 'gesprochen'),
    ('sprießen', 'spross', 'gesprossen'), ('springen', 'sprang', 'gesprungen'),
    ('stechen', 'stach', 'gestochen'), ('stehen', 'stand', 'gestanden'),
    ('stehlen', 'stahl', 'gestohlen'), ('steigen', 'stieg', 'gestiegen'),
    ('sterben', 'starb', 'gestorben'), ('stinken', 'stank', 'gestunken'),
    ('stoßen', 'stieß', 'gestoßen'), ('streichen', 'strich', 'gestrichen'),
    ('streiten', 'stritt', 'gestritten'), ('tragen', 'trug', 'getragen'),
    ('treffen', 'traf', 'getroffen'), ('treiben', 'trieb', 'getrieben'),
    ('treten', 'trat', 'getreten'), ('trinken', 'trank', 'getrunken'),
    ('tun', 'tat', 'getan'), ('verderben', 'verdarb', 'verdorben'),
    ('vergessen', 'vergaß', 'vergessen'), ('verlieren', 'verlor', 'verloren'),
    ('wachsen', 'wuchs', 'gewachsen'), ('waschen', 'wusch', 'gewaschen'),
    ('weisen', 'wies', 'gewiesen'), ('wenden', 'wandte', 'gewandt'),
    ('werben', 'warb', 'geworben'), ('werden', 'wurde', 'geworden'),
    ('werfen', 'warf', 'geworfen'), ('wiegen', 'wog', 'gewogen'),
    ('wissen', 'wusste', 'gewusst'), ('wollen', 'wollte', 'gewollt'),
    ('ziehen', 'zog', 'gezogen'), ('zwingen', 'zwang', 'gezwungen')
]

REGULAR_VERBS = [
    ('machen', 'machte', 'gemacht'), ('sagen', 'sagte', 'gesagt'),
    ('fragen', 'fragte', 'gefragt'), ('arbeiten', 'arbeitete', 'gearbeitet'),
    ('leben', 'lebte', 'gelebt'), ('lieben', 'liebte', 'geliebt'),
    ('hassen', 'hasste', 'gehasst'), ('kaufen', 'kaufte', 'gekauft'),
    ('verkaufen', 'verkaufte', 'verkauft'), ('lernen', 'lernte', 'gelernt'),
    ('lehren', 'lehrte', 'gelehrt'), ('studieren', 'studierte', 'studiert'),
    ('spielen', 'spielte', 'gespielt'), ('tanzen', 'tanzte', 'getanzt'),
    ('kochen', 'kochte', 'gekocht'), ('putzen', 'putzte', 'geputzt'),
    ('aufräumen', 'räumte auf', 'aufgeräumt'), ('einkaufen', 'kaufte ein', 'eingekauft'),
    ('reisen', 'reiste', 'gereist'), ('wandern', 'wanderte', 'gewandert'),
    ('malen', 'malte', 'gemalt'), ('zeichnen', 'zeichnete', 'gezeichnet'),
    ('lachen', 'lachte', 'gelacht'), ('weinen', 'weinte', 'geweint'),
    ('hören', 'hörte', 'gehört'), ('warten', 'wartete', 'gewartet'),
    ('brauchen', 'brauchte', 'gebraucht'), ('glauben', 'glaubte', 'geglaubt'),
    ('hoffen', 'hoffte', 'gehofft'), ('zählen', 'zählte', 'gezählt'),
    ('bezahlen', 'bezahlte', 'bezahlt'), ('öffnen', 'öffnete', 'geöffnet'),
    ('schließen', 'schloss', 'geschlossen'), ('antworten', 'antwortete', 'geantwortet'),
    ('danken', 'dankte', 'gedankt'), ('feiern', 'feierte', 'gefeiert'),
    ('rauchen', 'rauchte', 'geraucht'), ('schauen', 'schaute', 'geschaut'),
    ('zeigen', 'zeigte', 'gezeigt'), ('wohnen', 'wohnte', 'gewohnt'),
    ('suchen', 'suchte', 'gesucht'), ('besuchen', 'besuchte', 'besucht'),
    ('frühstücken', 'frühstückte', 'gefrühstückt'), ('kosten', 'kostete', 'gekostet'),
    ('parken', 'parkte', 'geparkt'), ('planen', 'plante', 'geplant'),
    ('regnen', 'regnete', 'geregnet'), ('schneien', 'schneite', 'geschneit'),
    ('sparen', 'sparte', 'gespart'), ('üben', 'übte', 'geübt'),
    ('übersetzen', 'übersetzte', 'übersetzt'), ('wünschen', 'wünschte', 'gewünscht'),
    ('gehören', 'gehörte', 'gehört'), ('passieren', 'passierte', 'passiert'),
    ('probieren', 'probierte', 'probiert'), ('reservieren', 'reservierte', 'reserviert'),
    ('reparieren', 'reparierte', 'repariert'), ('erklären', 'erklärte', 'erklärt'),
    ('erzählen', 'erzählte', 'erzählt'), ('verdienen', 'verdiente', 'verdient'),
    ('wiederholen', 'wiederholte', 'wiederholt'), ('küssen', 'küsste', 'geküsst'),
    ('legen', 'legte', 'gelegt'), ('stellen', 'stellte', 'gestellt'),
    ('gähnen', 'gähnte', 'gegähnt'), ('atmen', 'atmete', 'geatmet'),
    ('baden', 'badete', 'gebadet'), ('bauen', 'baute', 'gebaut'),
    ('dauern', 'dauerte', 'gedauert'), ('drücken', 'drückte', 'gedrückt'),
    ('duschen', 'duschte', 'geduscht'), ('fühlen', 'fühlte', 'gefühlt'),
    ('heiraten', 'heiratete', 'geheiratet'), ('holen', 'holte', 'geholt'),
    ('informieren', 'informierte', 'informiert'), ('klettern', 'kletterte', 'geklettert'),
    ('kleben', 'klebte', 'geklebt'), ('klopfen', 'klopfte', 'geklopft'),
    ('landen', 'landete', 'gelandet'), ('lächeln', 'lächelte', 'gelächelt'),
    ('mieten', 'mietete', 'gemietet'), ('organisieren', 'organisierte', 'organisiert'),
    ('packen', 'packte', 'gepackt'), ('putzen', 'putzte', 'geputzt'),
    ('rechnen', 'rechnete', 'gerechnet'), ('reden', 'redete', 'geredet'),
    ('schaden', 'schadete', 'geschadet'), ('schaffen', 'schaffte', 'geschafft'),
    ('schenken', 'schenkte', 'geschenkt'), ('schicken', 'schickte', 'geschickt'),
    ('schmecken', 'schmeckte', 'geschmeckt'), ('schützen', 'schützte', 'geschützt'),
    ('setzen', 'setzte', 'gesetzt'), ('stören', 'störte', 'gestört'),
    ('studieren', 'studierte', 'studiert'), ('tanken', 'tankte', 'getankt'),
    ('töten', 'tötete', 'getötet'), ('träumen', 'träumte', 'geträumt'),
    ('trennen', 'trennte', 'getrennt'), ('trocknen', 'trocknete', 'getrocknet'),
    ('verdienen', 'verdiente', 'verdient'), ('vermissen', 'vermisste', 'vermisst'),
    ('verstehen', 'verstand', 'verstanden'), ('vorbereiten', 'bereitete vor', 'vorbereitet'),
    ('wählen', 'wählte', 'gewählt'), ('wechseln', 'wechselte', 'gewechselt'),
    ('wecken', 'weckte', 'geweckt'), ('zelten', 'zeltete', 'gezeltet'),
    ('zerstören', 'zerstörte', 'zerstört'), ('abholen', 'holte ab', 'abgeholt'),
    ('anrufen', 'rief an', 'angerufen'), ('aufhören', 'hörte auf', 'aufgehört'),
    ('aufmachen', 'machte auf', 'aufgemacht'), ('aufräumen', 'räumte auf', 'aufgeräumt'),
    ('aufwachen', 'wachte auf', 'aufgewacht'), ('aussehen', 'sah aus', 'ausgesehen'),
    ('einladen', 'lud ein', 'eingeladen'), ('einschlafen', 'schlief ein', 'eingeschlafen'),
    ('fernsehen', 'sah fern', 'ferngesehen'), ('mitbringen', 'brachte mit', 'mitgebracht'),
    ('mitkommen', 'kam mit', 'mitgekommen'), ('teilnehmen', 'nahm teil', 'teilgenommen'),
    ('umbringen', 'brachte um', 'umgebracht'), ('umziehen', 'zog um', 'umgezogen'),
    ('vorhaben', 'hatte vor', 'vorgehabt'), ('vorschlagen', 'schlug vor', 'vorgeschlagen'),
    ('weglaufen', 'lief weg', 'weggelaufen'), ('zuhören', 'hörte zu', 'zugehört'),
    ('zumachen', 'machte zu', 'zugemacht'), ('zurückkommen', 'kam zurück', 'zurückgekommen'),
    ('anfangen', 'fing an', 'angefangen'), ('anbieten', 'bot an', 'angeboten'),
    ('anziehen', 'zog an', 'angezogen'), ('ausgeben', 'gab aus', 'ausgegeben'),
    ('beschreiben', 'beschrieb', 'beschrieben'), ('bestehen', 'bestand', 'bestanden'),
    ('diskutieren', 'diskutierte', 'diskutiert'), ('entscheiden', 'entschied', 'entschieden'),
    ('erfinden', 'erfand', 'erfunden'), ('erlauben', 'erlaubte', 'erlaubt'),
    ('fotografieren', 'fotografierte', 'fotografiert'), ('funktionieren', 'funktionierte', 'funktioniert'),
    ('gefallen', 'gefiel', 'gefallen'), ('gratulieren', 'gratulierte', 'gratuliert'),
    ('interessieren', 'interessierte', 'interessiert'), ('kombinieren', 'kombinierte', 'kombiniert'),
    ('kontrollieren', 'kontrollierte', 'kontrolliert'), ('kopieren', 'kopierte', 'kopiert'),
    ('passieren', 'passierte', 'passiert'), ('produzieren', 'produzierte', 'produziert'),
    ('telefonieren', 'telefonierte', 'telefoniert'), ('verbieten', 'verbot', 'verboten'),
    ('vergleichen', 'verglich', 'verglichen'), ('versprechen', 'versprach', 'versprochen'),
    ('vorlesen', 'las vor', 'vorgelesen'), ('waschen', 'wusch', 'gewaschen'),
    ('wegwerfen', 'warf weg', 'weggeworfen'), ('widersprechen', 'widersprach', 'widersprochen'),
    ('zurückgeben', 'gab zurück', 'zurückgegeben')
][:len(IRREGULAR_VERBS)]